#!/bin/bash
#
# Pre-commit hooks

# Check branch name

regex="^(feat|fix|hotfix|chore|refactor|docs)_.+_OLT-\d{4}$|^(release)_v\d{1,}.\d{1,}.\d{1,}$"

BRANCH_NAME_LENGTH=`git rev-parse --abbrev-ref HEAD | grep -E $regex | wc -c`

if [ ${BRANCH_NAME_LENGTH} -eq 0 ] ; then
  echo -e "ERROR in branch-name hook: /scripts/branch-name"
  echo "Branch name should match one of the patterns: branchType_whatever_OLT-XXXX, where XXXX is the Jira ticket number"
  echo "and branchType is one of: feat, fix, hotfix, chore, refactor, docs"
  echo "or release_vX.X.X where X.X.X is the version number"
  echo "Skip pre-commit hooks with --no-verify (not recommended)."
  exit 1
fi
